### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Smile2day-Enterprise**

### CODE REVIEW

**Comment by djprmf** [comment]
EZBlocker is working just fine in the last version of Spotify...
ez

This update to the readme doesnt make sense...

**Comment by Smile2day-Enterprise** [comment]
Doesn't work on windows 10. Have you tested it on win10?

**Comment by mhujer** [comment]
Works for me on W10. You need to start Spotify before starting EZBlocker, otherwise it hangs.

**Comment by djprmf** [comment]
yes, working on Windows 10. For me i have to start first the EZBlocker (he opens the spotify automatically, so no need of other action) and only minimize EZ when a music starts playing...

**Comment by Stanzilla** [comment]
Still no reason to do this as a *Pull Request*, create an issue instead if you have a problem.

**Pull request closed without merging**
