### PR TITLE
Made changes for considering MS Store version

### PR DESCRIPTION
**Pull request by gnpaone**
Just tried to address #261, if necessary to change the same thing in various code files, please make it, like this feature to work on store version too 😊

### CODE REVIEW

**Comment by mendelsphotography** [comment]
Just saying from what It looks like you would need to re-patch it for each Update.

**Comment by gnpaone** [comment]
> Just saying from what It looks like you would need to re-patch it for each Update.

No, there is no need for that, because ms store version spotify updates are released under the same id as in the mentioned changes, I recently updated my Spotify and it will still show the same 2017 version number (in ms store but not in Spotify) even though it's being updated, so there is no need for re-patching. You can verify it through ms store or adguard:
Screenshot (5650)
Screenshot (5649)

In Spotify: (it's updated to latest 2022 version but see the version number)
image

You can verify it by yourself too

**Comment by mendelsphotography** [comment]
Ok, Great Well Like I say That's what's great about open sources even until your pull request gets merged anybody can simply recompile it themself it's not that hard with C#. So even if a project is dead and you know some coding and the language it made it is not always hard to patch or fix it.

**Comment by gnpaone** [comment]
Yeah

**Comment by mendelsphotography** [comment]
I would suggest making a comment on the issue and letting people know that they can recompile the code themself with your fix until it's patched by adding that code.

**Comment by gnpaone** [comment]
> I would suggest making a comment on the issue and letting people know that they can recompile the code themself with your fix until it's patched by adding that code. 

Then probably it will take some time for me to go through all codes where changes needed and then commit and add changes, I thought @Xeroday or any contributors may help and it'd be great

**Comment by mendelsphotography** [comment]
It looks like this is a side project and not fully on top of it As many of us devs do Make fun ideas or projects and are too busy to maintain it all the time. Sometimes when you start out you build all kinds of nice stuff and then get a job and forget about it or don't have free time to work on it. Well, that's why I like free and open-source software since you can always fork the project and make your own changes and if someone has issues and they trust you they can use your fixed or maintained fork as long the License allows that.

**Pull request closed without merging**
